apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend-vs
  namespace: bebop
spec:
  hosts:
    - "bebop.lan" # same host as Gateway
  gateways:
    - app-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: frontend.bebop.svc.cluster.local
            port:
              number: 8000
